"""Initial migration

Revision ID: 47923d528e3e
Revises: 
Create Date: 2025-07-19 14:06:14.539365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47923d528e3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 